export const fetchDashboardData = async () => {
  return {
    storeCustomers: [
      {
        id: 1,
        name: "علي احمد كريم",
        age: 22,
        gender: "ذكر",
        joinDate: "2024/8/13",
        pointOfReference: "قرب اسواق مشمشة",
        city: "بابل",
        subCity: "الحلة",
        phoneNumber: "1",
        orders: [
          {
            id: 1,
            productName: "صابون",
            productRepetition: "شهري",
            productType: "عناية",
            time: "1234",
            productPrice: 1000,
          },
          {
            id: 2,
            productName: "غسول وجة",
            productRepetition: "شهري",
            productType: "عناية",
            time: "5678",
            productPrice: 1100,
          },
          {
            id: 3,
            productName: "عطر",
            productRepetition: "شهري",
            productType: "عناية",
            time: "9101",
            productPrice: 1200,
          },
          {
            id: 4,
            productName: "معطر",
            productRepetition: "شهري",
            productType: "عناية",
            time: "1213",
            productPrice: 1300,
          },
          {
            id: 5,
            productName: "مرطب",
            productRepetition: "شهري",
            productType: "عناية",
            time: "1415",
            productPrice: 1400,
          },
        ],
      },
      {
        id: 2,
        name: "كاظم احمد كريم",
        age: 24,
        gender: "ذكر",
        joinDate: "2024/3/13",
        pointOfReference: "قرب اسواق مشمشة",
        city: "بابل",
        subCity: "الحلة",
        phoneNumber: "12",
        orders: [],
      },
      {
        id: 3,
        name: "محمد جاسم كريم",
        age: 28,
        gender: "ذكر",
        joinDate: "2024/1/13",
        pointOfReference: "قرب اسواق مشمشة",
        city: "بابل",
        subCity: "الحلة",
        phoneNumber: "123",
        orders: [],
      },
      {
        id: 4,
        name: "محمد جاسم كريم",
        age: 28,
        gender: "ذكر",
        joinDate: "2024/1/13",
        pointOfReference: "قرب اسواق مشمشة",
        city: "بابل",
        subCity: "الحلة",
        phoneNumber: "1234",
        orders: [],
      },
      {
        id: 5,
        name: "محمد جاسم كريم",
        age: 28,
        gender: "ذكر",
        joinDate: "2024/1/13",
        pointOfReference: "قرب اسواق مشمشة",
        city: "بابل",
        subCity: "الحلة",
        phoneNumber: "12345",
        orders: [],
      },
      {
        id: 6,
        name: "محمد جاسم كريم",
        age: 28,
        gender: "ذكر",
        joinDate: "2024/1/13",
        pointOfReference: "قرب اسواق مشمشة",
        city: "بابل",
        subCity: "الحلة",
        phoneNumber: "123456",
        orders: [],
      },
      {
        id: 7,
        name: "محمد جاسم كريم",
        age: 28,
        gender: "ذكر",
        joinDate: "2024/1/13",
        pointOfReference: "قرب اسواق مشمشة",
        city: "بابل",
        subCity: "الحلة",
        phoneNumber: "1234567",
        orders: [],
      },
      {
        id: 8,
        name: "محمد جاسم كريم",
        age: 28,
        gender: "ذكر",
        joinDate: "2024/1/13",
        pointOfReference: "قرب اسواق مشمشة",
        city: "بابل",
        subCity: "الحلة",
        phoneNumber: "12345678",
        orders: [],
      },
      {
        id: 9,
        name: "محمد جاسم كريم",
        age: 28,
        gender: "ذكر",
        joinDate: "2024/1/13",
        pointOfReference: "قرب اسواق مشمشة",
        city: "بابل",
        subCity: "الحلة",
        phoneNumber: "123456789",
        orders: [],
      },
      {
        id: 10,
        name: "محمد جاسم كريم",
        age: 28,
        gender: "ذكر",
        joinDate: "2024/1/13",
        pointOfReference: "قرب اسواق مشمشة",
        city: "بابل",
        subCity: "الحلة",
        phoneNumber: "1234567890",
        orders: [],
      },
      {
        id: 11,
        name: "محمد جاسم كريم",
        age: 28,
        gender: "ذكر",
        joinDate: "2024/1/13",
        pointOfReference: "قرب اسواق مشمشة",
        city: "بابل",
        subCity: "الحلة",
        phoneNumber: "12345678901",
        orders: [],
      },
    ],
    products: [
      {
        id: 1,
        productName: "صابون",
        productRepetition: "شهري",
        productType: "عناية",
        time: "1234",
        productPrice: 1000,
      },
      {
        id: 2,
        productName: "غسول وجة",
        productRepetition: "شهري",
        productType: "عناية",
        time: "5678",
        productPrice: 1100,
      },
      {
        id: 3,
        productName: "عطر",
        productRepetition: "شهري",
        productType: "عناية",
        time: "9101",
        productPrice: 1200,
      },
      {
        id: 4,
        productName: "معطر",
        productRepetition: "شهري",
        productType: "عناية",
        time: "1213",
        productPrice: 1300,
      },
      {
        id: 5,
        productName: "مرطب",
        productRepetition: "شهري",
        productType: "عناية",
        time: "1415",
        productPrice: 1400,
      },
      {
        id: 6,
        productName: "صابون",
        productRepetition: "شهري",
        productType: "عناية",
        time: "1617",
        productPrice: 1500,
      },
      {
        id: 7,
        productName: "صابون",
        productRepetition: "شهري",
        productType: "عناية",
        time: "1819",
        productPrice: 1600,
      },
      {
        id: 8,
        productName: "صابون",
        productRepetition: "شهري",
        productType: "عناية",
        time: "2020",
        productPrice: 1700,
      },
      {
        id: 9,
        productName: "صابون",
        productRepetition: "شهري",
        productType: "عناية",
        time: "2222",
        productPrice: 1800,
      },
      {
        id: 10,
        productName: "صابون",
        productRepetition: "شهري",
        productType: "عناية",
        time: "2424",
        productPrice: 1900,
      },
      {
        id: 11,
        productName: "صابون",
        productRepetition: "شهري",
        productType: "عناية",
        time: "2626",
        productPrice: 2000,
      },
    ],
    topProducts: [
      { product: "صابون", count: 186 },
      { product: "غسول وجه", count: 237 },
      { product: "عطر", count: 305 },
      { product: "مكياج", count: 73 },
      { product: "شامبو", count: 209 },
      { product: "حمرة", count: 214 },
    ],
    yearSummary: [
      { month: "January", income: 1860 },
      { month: "February", income: 3050 },
      { month: "March", income: 2370 },
      { month: "April", income: 730 },
      { month: "May", income: 2090 },
      { month: "June", income: 2140 },
      { month: "July", income: 1860 },
      { month: "August", income: 3050 },
      { month: "September", income: 2370 },
      { month: "October", income: 730 },
      { month: "November", income: 2090 },
      { month: "December", income: 2140 },
    ],
    topCities: [
      { city: "بغداد", count: 275 },
      { city: "بابل", count: 200 },
      { city: "اربيل", count: 187 },
      { city: "ديوانية", count: 173 },
      { city: "بصرة", count: 90 },
    ],
    customers: [
      {
        id: 1,
        name: "احمد محمد",
        count: 1999,
        avatar: null,
      },
      {
        id: 2,
        name: "علي حسن",
        count: 1500,
        avatar: null,
      },
      {
        id: 3,
        name: "فاطمة كاظم",
        count: 1200,
        avatar: null,
      },
      {
        id: 4,
        name: "احمد محمد",
        count: 1999,
        avatar: null,
      },
      {
        id: 5,
        name: "علي حسن",
        count: 1500,
        avatar: null,
      },
    ],
  };
};
